spring:
  application:
    name: Home-4-You
    version: "@project.version@"
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/home-4-you
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      show-sql: true
      ddl-auto: none
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
