server:
  port: 8000
spring:
  application:
    name: Home-4-You
    version: "@project.version@"
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/home-4-you
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      show-sql: true
      ddl-auto: none
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 788461512059-up6tko05mahee5d4jn97fag6mvisl2l2.apps.googleusercontent.com
            clientSecret: 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
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

home-4-you:
  auth:
    jwtSecret: aG9tZV80X3lvdV9zZWNyZXRfa2V5
    expirationTime: 864000000
  cors:
    allowed-origins: "*"
    allowed-headers:
      - Authorization
      - Content-Type
    allowed-methods:
      - GET
      - PUT
      - POST
      - DELETE
      - PATCH
      - OPTIONS

logging:
  level:
    org:
      springframework:
        security: TRACE
