spring:
  application:
    name: Home 4 You
  datasource:
    url: jdbc:postgresql://localhost:5432/home-4-you
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: true
      ddl-auto: none
#      ddl-auto: create-drop
  sql:
    init:
#      mode: always
#      mode: never
